import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header"
import Hero from "../components/Hero"

const Home: NextPage = () => {
  return (
    <div className= "bg-[#040404] text-[#2272FF] h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Lukas' Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />\\
      </Head>


      <Header/>

      {/* Hero */}
      <section id = "hero" className="snap-center">
        <Hero />
      </section>

      {/* About */}

      {/* Experience */}

      {/* Skills */}

      {/* Projects */}

      {/* Contact Me */}

    
    </div>
  )
}

export default Home
